### ISSUE TITLE
Ability to remove the InkWell splashColor effect

### ISSUE THREAD

**Issue by briceallard** [vipulasri/flutter_bubble_tab_indicator#2]
Is there a way to disable to effect you get when tapping the Tab items?
![image](https://user-images.githubusercontent.com/25207870/60404448-b3fe3500-9b6e-11e9-9574-7a766ba80b79.png)

**Comment by malviyaritesh** [comment]
@briceallard

Here's a hack:
You can set `flexibleSpace` property of `AppBar` as follows:
```dart
flexibleSpace: DecoratedBox(
  decoration: BoxDecoration(
    color: Theme.of(context).primaryColor,
  ),
  child: FlexibleSpaceBar(),
),
```

**Comment by vipinnegi90** [comment]
> 
> 
> @briceallard
> 
> Here's a hack:
> You can set `flexibleSpace` property of `AppBar` as follows:
> 
> ```dart
> flexibleSpace: DecoratedBox(
>   decoration: BoxDecoration(
>     color: Theme.of(context).primaryColor,
>   ),
>   child: FlexibleSpaceBar(),
> ),
> ```

what if AppBar is not used for Tabs?

**Comment by vipinnegi90** [comment]
> 
> 
> @briceallard
> 
what if AppBar is not used for Tabs?

**Comment by vipulasri** [comment]
It's not related to the library. Please check: https://github.com/flutter/flutter/issues/20250
