### ISSUE TITLE
Unselected Indicator Color

### ISSUE THREAD

**Issue by OliverNarramore** [vipulasri/flutter_bubble_tab_indicator#3]
Is there a way to add a color to unselected indicators? Thank you

**Comment by vipulasri** [comment]
@OliverNarramore are you talking about unselected text color?

**Comment by dagovalsusa** [comment]
> Is there a way to add a color to unselected indicators? Thank you
>> @OliverNarramore are you talking about unselected text color?

add a background color to unselected indicator, it is possible?

**Comment by mohadel92** [comment]
is it possible?@

**Comment by dagovalsusa** [comment]
> is it possible?@

Switch to https://github.com/Akiat/flutter_tags
